# A Travis is a service that provides Continuous Integration (CI) freely for
# Open-Source projects.
# It can be integrated with GitHub, by making a build each time new code is pushed.
# This is also done with PRs (Pull Requests), which can be rejected if failing the builds.

# Specify we are working with a Java project.
# Travis can be used also for many other languages.
language: java

# The JDK we need for compiling
jdk:
  - openjdk11

# In some examples, we will use NodeJS as runtime to run JavaScript code
node_js:
  - node


# "sudo" is a Linux/Bash command to execute other commands in super-user (ie "root")
# mode. This is needed in Travis when using Docker
sudo: true

# Specify we need Docker for our build
services:
  - docker


# As the build will download JAR files from Maven Central, optimize their storage,
# so they do not get re-downloaded each time
cache:
  directories:
    - .autoconf
    - $HOME/.m2

# Useful when working in team. If someone breaks the build (code does not compile
# or some tests are failing), then get notified by email immediately.
notifications:
  email: true


# The actual command we do for compiling.
# Note: Travis has a quite limited handling of build log files, so need
# to minimize them, ie do not be too verbose
script: mvn clean verify --fae

os: osx